### ISSUE TITLE
Bitcoin Cash / BCC?

### ISSUE THREAD

**Issue by npomfret** [crypti/cryptocurrencies#15]
Hi

Why is BCH mapped to _Bitcoin Cash / BCC_?  Surely the name is just _Bitcoin Cash_?  I understand that a few exchanges use a different symbol, but that's the same with bitcoin (XBT) and I'm sure some others.  Can we change it?

**Comment by radiovisual** [comment]
This was fixed via https://github.com/crypti/cryptocurrencies/commit/d23e7147879540c6308e6a31ededc65dac1b4846#diff-34b3e8c2daedd0451fc0f1eb5f45af12R308, it was just the way that the API we are using had the name mapped, looks like they have fixed it it. 👍
