### ISSUE TITLE
Symbol change for BitCurrency

### ISSUE THREAD

**Issue by rwdim** [crypti/cryptocurrencies#17]
BitCurrency (BTCR) is now symbol BC

https://bitcointalk.org/index.php?topic=3369654.msg40915825#msg40915825

Cheers!

**Comment by radiovisual** [comment]
It appears that BitCurrency is still seen as `BTCR` according to the [cryptocompare API](https://www.cryptocompare.com/coins/btcr/overview), which means the change in symbol request should be sent directly to them, so that this list will pick up on the change automatically.

**Comment by pml10628** [comment]
RealBank(RBT)
