### ISSUE TITLE
MIOTA

### ISSUE THREAD

**Issue by siboulet** [crypti/cryptocurrencies#18]
Please consider adding MIOTA which is the correct supply symbol for IOTA.

**Comment by radiovisual** [comment]
This list is auto-generated from the cryptocompare API. So to see changes on this list, you would need to request the change from https://www.cryptocompare.com/(use the `Contact us` link at the bottom), then when they have made the update, this list will pick on the change by running `npm run build` and opening a PR, or updating this thread with a note that the change has been made upstream.

**Comment by radiovisual** [comment]
With that said, the list has been updated to include the correct symbol name
