### ISSUE TITLE
Procoin

### ISSUE THREAD

**Issue by thonguyen122** [crypti/cryptocurrencies#23]

**Comment by radiovisual** [comment]
The coins are named as they appear on the Coinbase API, and this list is auto-generated, so making manual updates to the coin names would be overwritten by the auto-generated list. I am not sure if all you meant was you preferred that the coin be spelled differently, but your issue does not have a description, so I will assume you just wanted a coin to be spelled differently. For that to happen the coin name would be need to be spelled differently on the Coinbase API.
