### ISSUE TITLE
XRP

### ISSUE THREAD

**Issue by joska1993** [crypti/cryptocurrencies#24]
Thank you very much for everything.

A suggestion, you could put "XRP" as "Ripple".

**Comment by radiovisual** [comment]
The coins are named as they appear on the Coinbase API, and this list is auto-generated, so making manual updates to the coin names would be overwritten by the auto-generated list. I have thought about maintaining a list of overrides, which could allow us to assign some "nicknames" to the coins, but I don't have a lot of extra time to maintain or curate this list.
