### ISSUE TITLE
Match with Wikidata items

### ISSUE THREAD

**Issue by Manu1400** [crypti/cryptocurrencies#3]
Example : EagleCoin -> https://www.wikidata.org/wiki/Q20639637

Note: use `sameAs: "https://www.wikidata.org/wiki/Q20639637"`

**Comment by radiovisual** [comment]
@Manu1400, can you be more specific about your request? I am not sure what you mean. Thanks!

**Comment by radiovisual** [comment]
I am going to close this issue, since this list of just meant to be a simple JSON reference from the currencies that are collected by the cryptocompare API. But anyone is welcome to submit a PR with extended functionality if they want to help add value to this resource. 👍
